// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_HC3o2odCT6EM03-fi3VhXQzFcEPx6AY',
    appId: '1:237115204767:web:5b60c2926eb124e0712eaa',
    messagingSenderId: '237115204767',
    projectId: 'rfid-room-manager',
    authDomain: 'rfid-room-manager.firebaseapp.com',
    storageBucket: 'rfid-room-manager.firebasestorage.app',
    measurementId: 'G-BT3VJKMS64',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyTIdqRsU9LKXp7XcZswbCAE2ehqwyrRU',
    appId: '1:237115204767:android:c4df34dd193599f1712eaa',
    messagingSenderId: '237115204767',
    projectId: 'rfid-room-manager',
    storageBucket: 'rfid-room-manager.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnxpQexJr_0WhkWsg29tDZ_IHqo-sm6fM',
    appId: '1:237115204767:ios:6e770424cec11322712eaa',
    messagingSenderId: '237115204767',
    projectId: 'rfid-room-manager',
    storageBucket: 'rfid-room-manager.firebasestorage.app',
    iosBundleId: 'com.example.sallemanager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnxpQexJr_0WhkWsg29tDZ_IHqo-sm6fM',
    appId: '1:237115204767:ios:6e770424cec11322712eaa',
    messagingSenderId: '237115204767',
    projectId: 'rfid-room-manager',
    storageBucket: 'rfid-room-manager.firebasestorage.app',
    iosBundleId: 'com.example.sallemanager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_HC3o2odCT6EM03-fi3VhXQzFcEPx6AY',
    appId: '1:237115204767:web:b0c57882f15b57c6712eaa',
    messagingSenderId: '237115204767',
    projectId: 'rfid-room-manager',
    authDomain: 'rfid-room-manager.firebaseapp.com',
    storageBucket: 'rfid-room-manager.firebasestorage.app',
    measurementId: 'G-DHZCR7B4B2',
  );
}
